# borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# lint it here: http://lint.travis-ci.org/ 
language: python
python:
  - 2.7
notifications:
  email: false
  
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update --yes conda
  - deps='numpy pandas scipy matplotlib ipython scikit-learn paramiko pil cclib chemview pyopengl==3.0.2 chemlab nose nose-parameterized'
  - conda create -p $HOME/py --yes -c https://conda.binstar.org/cjs14 python=$TRAVIS_PYTHON_VERSION $deps
  - export PATH=$HOME/py/bin:$PATH
  - python setup.py install
# Run test
script:
  - "nosetests -v"
