# borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# lint it here: http://lint.travis-ci.org/ 
language: python
python:
  - 2.7
notifications:
  email: false

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:/home/travis/miniconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis and
  # are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda update --yes conda
# Install conda packages
install:
  - deps='numpy pandas scipy matplotlib ipython scikit-learn paramiko pil cclib chemview pyopengl==3.0.2 chemlab nose nose-parameterized'
  - conda install --yes -c https://conda.binstar.org/cjs14 python=$TRAVIS_PYTHON_VERSION $deps
  - python setup.py install
# Run test
script:
  - nosetests -v --nocapture
